name: 'File Copy'
description: 'This is test actions'
inputs:
 HiName:
  description: 'Give name'
  required: false
  default: 'Rahul'
 
runs:
  using: 'composite'
  steps:
   - run: echo 'Hiiiiiiiiiiiiii'
     shell: bash
 
