name: Comp eg

on: [workflow_dispatch]

jobs:
  myjob:
   runs-on: ubuntu-latest
   name: a job that say hi.
   steps:
   - uses: actions/checklout@v2
   - id: rahulshitole
     uses: shitole18/TestCases@v1
     with:
      HiName: 'Rahul'
   - run: echo 'rahul his'
     shell: bash
