name: .NET

on:
  push:
    branches: [ main,test ]
  pull_request:
    branches: [ main,test ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore "~/../TestProject1/TestProject1.csproj"
    - name: Build
      run: dotnet build "~/../TestProject1/TestProject1.csproj" --no-restore
    - name: Test
      run: dotnet test "~/../TestProject1/TestProject1.csproj" --no-build --verbosity normal
    - name: Step a
      run: |
        echo "The GitHub Action Secret will be masked"
        echo ${{secrets.SNAME}}
        echo "Trick to echo GitHub Actions Secret"
        echo ${{secrets.PASSWORD}} | sed 's/./& /g'
    - name: Echo Secrets
      run: |
         echo ${{secrets.PASSWORD}} 
         echo ${{secrets.SNAME}} 



