name: .Hallu

on:
  push:
    branches: [ main,test ]
  pull_request:
    branches: [ main,test ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "Hello world from template."  
    - name: Step 2 - GitHub Action if statement (true)
      env: 
       WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
      if:  env.WHO_TO_TRUST == 'TrustNo1'
      run: echo "I know what the secret token is!"
    - name: Echo Secrets
      run: |
         echo ${{secrets.PASSWORD}} 
         echo ${{secrets.SNAME}} 
