name: Compact

on:
  push:
    branches: [ main,mytesting_actions]
  pull_request:
    branches: [ main,mytesting_actions]

env:
   OUTPUT_SUFFIX: MySuffix

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: CompositeAction Demo
    steps: 
     - uses: actions/checkout@v1
     - name: My first step
       uses: ./
       with:
          MYNAME: 'rahul'
     - uses: actions/checkout@v1
     - name: My second step
       uses: ./.github\workflows/
       with:
          MYNAME: 'sujay'