name: Compact

on:
  push:
    branches: [ main,mytesting_actions]
  pull_request:
    branches: [ main,mytesting_actions]
    
jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps: 
     - uses: actions/checkout@v1
     - name: My first step
       uses: ./
       with:
          who-to-greet: 'Mona the Octocat'
     - name: step2
       uses: ./
       with:
          who-to-greet: 'Mona the Octocat'
     - name: step3
       uses: ./
       with:
          who-to-greet: 'Mona the Octocat'
     - run: echo random-number ${{ steps.foo.outputs.random-number }}
       shell: bash
