name: Compact

on:
  push:
    branches: [ main,mytesting_actions]
  pull_request:
    branches: [ main,mytesting_actions]
    
jobs:
  hello_world_job:
    runs-on: windows-latest
    name: CompositeAction Demo
    steps: 
     - uses: actions/checkout@v1
     - name: My first step
       uses: ./
       with:
          MYNAME: 'rahul'